### ISSUE TITLE
Basic ERD

### ISSUE THREAD

**Issue by vangp42** [FriendlyCuisine/WebApplication#2]
Create a basic ERD

**Comment by vangp42** [comment]
Completed

**Comment by robnelson1988** [comment]
Below is the link to the Basic ERD we all worked in through weeks 1-2. A file is also attached for download.
[CSC 450 Capstone ERD Group B.pdf](https://github.com/FriendlyCuisine/WebApplication/files/3693483/CSC.450.Capstone.ERD.Group.B.pdf)


https://www.lucidchart.com/documents/edit/98183cd2-40ea-412f-8889-1c38cb31fa09
